import { useState } from 'react'
import Head from 'next/head'

import Header from '@/components/organisms/Header'
import Sidebar from '@/components/organisms/Sidebar'

export default function Home() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Boketto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header setIsSidebarOpen={setIsSidebarOpen} />
        {isSidebarOpen && <Sidebar setIsSidebarOpen={setIsSidebarOpen} />}
      </main>
    </>
  )
}
